<div class="menuContainer">
<ul id="menu">
    <li><? echo Html::Link ('','Admin Avisoya KB')?></li>
    
    <li><? echo Html::Link ('adminc3/categoria','Categorias')?></li>
    <li><? echo Html::Link ('adminc3/ciudad','Ciudades')?></li>
    <li><? echo Html::Link ('adminc3/clasificados','Clasificados')?></li>

    <li><a href="#">Twitter <?php echo Html::img('arrow.png','desplegable','width="12" height="12"');?></a>
        <ul>
            <li><a href="catenuevo.php">Nuevo</a></li>
        </ul>
    </li>
</ul>
<div class="clear"></div>
</div>