<div class="row caja"><div class="page-header"><span class="lead">Clasificados Gratis Faciles y Rapidos con Twitter</span></div>
    <div class="col-md-12"><center>
            <?php echo html::link('oauth/_redirect', 'Iniciar con Twitter','class="zocial twitter" style="font-size:50px;"')?>
            <br><br><p>No tienes cuenta de twitter? <a href="https://twitter.com/" target="_blank">Creala ya</a> </p></center></div>
</div>