<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">
  <tr>
    <td align="center"><script type="text/javascript"><!--
google_ad_client = "ca-pub-2585826429536275";
/* 336x280, creado 21/07/11 avisoya */
google_ad_slot = "7927715738";
google_ad_width = 336;
google_ad_height = 280;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></td>
    <td align="center"><script type="text/javascript"><!--
google_ad_client = "ca-pub-2585826429536275";
/* 336x280, creado 21/07/11 avisoya */
google_ad_slot = "7927715738";
google_ad_width = 336;
google_ad_height = 280;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></td>
  </tr>
</table>
