<table width="100%" border="0" align="center">
<tr>
   
<!--tabla-->
    <td width="14%" valign="top">   
<!-- barra lateral izquierda nav   -->
        <?php View::partial('portal/lateral') ?>
    </td>  
<!--fin barra lateral izquierda nav    -->

    <td width="60%" valign="top">
<!--contenido-->


<!--lista clasificados-->
<br></br>
  <h1 style="font-size:24px; color:#F00">Acerca de Avisoya.com</h1>
  <p>&nbsp;</p>
  <p>&nbsp;</p>


<div style="font-weight:bold; font-size:22px; color:#999;">

  <h1>Avisoya  es la Nueva generación de anuncios gratis online.<br>
    <br>
    Avisoya provee una simple solución para las Ofertas implicadas en venta, compra, intercambio y promociones; de Articulos en comun  con gente cerca de ti, y donde quiera que te encuentres.<br>
    <br>
    En Avisoya tu puedes:</h1>
    <p>&nbsp;</p><br></br>
  <h2>Publicar facilmente un articulo gratituamente </h2>
  <ul>
    <li>
      <h2>      Controlar tu actividad en ventas, compras</h2>
    </li>
    <li>
      <h2>      Mostrar tus anuncios en tu perfil en otros sitios (Facebook, Twitter, ...)      </h2>
    </li>
    <li>
      <h2>      Acceder al sitio desde tu teléfono celular      </h2>
    </li>
    <li>
      <h2>Recibir comentarios de parte de los seguidores de tus articulos </h2>
    </li>
    <li></li>
</ul>
  <h2><br>
    Avisoya es usado en Colombia. La compañía fue fundada en Julio 2011 y es dirigida en forma privada.</h2>
  <h2><?php echo Html::img('fondo.png','',"style='width: 388px ;height: 361px'"); ?><br/>
  </h2><br>
  <h2>info@avisoya.com</h2>
    </div>

<!--fin lista clasificados-->
    </td>
    </tr>
</table>
    
