    <div class="row-fluid caja" style="padding: 20px">

<ul class="breadcrumb">
    <li><?php echo html::link('', 'Inicio') ?> <span class="divider">></span></li>
  <li><a href="#" class="active">Nosotros</a></li>
</ul>
   
<!-- barra lateral izquierda nav   -->
        <?php // View::partial('portal/lateral') ?>
<div style="font-weight:500; font-size:16px; color:#5A5A5A;">

  <center><h1 style="font-size:20px; color:#F00">Acerca de Avisoya.com</h1></center>
  <p>&nbsp;</p>
  <p>&nbsp;</p>



  <p>Avisoya  es la Nueva generación de anuncios gratis online.<br>
    <br>
    Avisoya provee una simple solución para las Ofertas implicadas en venta, compra, intercambio y promociones; de Articulos en comun  con gente cerca de ti, y donde quiera que te encuentres.<br>
    <br>
    En Avisoya tu puedes:</p>
    
    <p>&nbsp;</p><br></br>
  Publicar facilmente un articulo gratituamente
  <ul>
    <li>
          Controlar tu actividad en ventas, compras</h2>
    </li>
    <li>
         Mostrar tus anuncios en tu perfil en otros sitios (Facebook, Twitter, ...)      
    </li>
    <li>
            Acceder al sitio desde tu teléfono celular     
    </li>
    <li>
     Recibir comentarios de parte de los seguidores de tus articulos
    </li>
    <li></li>
</ul>
  <p><br>
    Avisoya es usado en Colombia. La compañía fue fundada en Julio 2011 y es dirigida en forma privada.</p>
  <h2><?php echo Html::img('fondo.png','',"style='width: 388px ;height: 361px'"); ?><br/>
  </h2><br>
  <h2>info@avisoya.com</h2>
    </div>

    
    </div>