 

<div class="navbar-bottom">
  <div class="panel-body">
  </div>
  <div class="panel-footer"><a href="#">Acerca de Avisoya</a>  |  <?php echo Html::Link('nosotros/','Clasificados Avisoya.com'); ?> | <a href="http://www.vendoaki.com" alt="Vendo, Compro, en Republica Dominicana" title="Vendo, Compro, en Republica Dominicana">Vender, Comprar en Republica Dominicana</a>  |  © <?php echo date('Y') ?></div>
</div>