<nav class="navbar navbar-orenge" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex2-collapse">
              
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <?php echo html::link('','Avisoya','class="navbar-brand"')?>
          <h2 class="tagline">Clasificados Faciles Rapidos y Gratis</h2>
        </div>
        <div class="collapse navbar-collapse navbar-ex2-collapse">
                      <?php echo html::link('publicar', 'Publica con <i class="icon-twitter icon-2x"></i>','class="navbar-right btn btn-primary navbar-btn" ')?>
                      <?php echo html::link('random/', '<i class="icon-random icon-2x"></i>','class="navbar-right btn btn-danger navbar-btn" ')?>
                      <?php echo html::link('editar/', '<i class="icon-pencil icon-2x"></i>','class="navbar-right btn btn-danger navbar-btn" ')?>

              <?php   if(Auth::is_valid()){ ?>
                <?php echo html::link('<i class="icon-signout"></i>', 'Publica con <i class="icon-twitter icon-2x"></i>','class="navbar-right btn btn-info navbar-btn" ')?>
              <?php }?>    
        </div>
      </nav>

