<div class="row-fluid"><div class="span10"><center>Clasificados Colombia</center></div><div class="span2"><div class="pull-right"><?php echo html::link('random', '<i class="icon-random"></i> ') ?> | <?php echo html::link('editar', 'Editar <i class="icon-twitter"></i>' )?> | <?php echo html::link('oauth/_logout', 'Salir <i class="icon-signout"></i>')?></div></div></div>
<div class="row-fluid" style="margin-top: 0px;">
    <div class="span9 header">
        <div class="row-fluid">
        <? echo html::link("", html::img('logo2.png','','width="300" style="padding:10px;"'), 'class="span6"') ?>
    <?php echo Form::open('buscar/','GET'); // por defecto llama a la misma url ?>
      <div class="input-append span6" style="margin-top:20px;">
          <center>  <?php echo Form::text('b'); ?>
          <button type="submit" class="btn"><i class="icon-search"></i></button></center>
      </div>
      <?php echo Form::close() ?>
        </div>
    </div>
    <div class="span3">
        <?php echo html::link('publicar', 'Publica con <i class="icon-twitter icon-2x"></i>','class="btn btn-large btn-primary" style="line-height: 44px; font-size:24px;"')?>
</div>
</div>