<div class="row-fluid"><div class="span10"><center>Clasificados Colombia</center></div><div class="span2"><div class="pull-right"><?php echo html::link('random', '<i class="icon-random"></i> ') ?> | <?php echo html::link('editar', 'Editar <i class="icon-twitter"></i>' )?> | <?php echo html::link('oauth/_logout', 'Salir <i class="icon-signout"></i>')?></div></div></div>
<div class="row-fluid" style="margin-top: 0px;">
    <div class="span9 header"><? echo html::link("", html::img('logo2.png','','width="400"'), 'class="span6"') ?><form class="form-search">

 
</form></div>
    <div class="span3">
        <?php //echo html::img('boton-publicar-twitter2.png') ?>
        <?php echo html::link('publicar', 'Publica con <i class="icon-twitter icon-2x"></i>','class="btn btn-large btn-warning" style="line-height: 23px; font-size:22px;"')?>
</div>
</div>