                <div class="page-header">
                    <span class="lead">Gratis Faciles y Rapidos</span>
                </div>
                    <?php // View::partial('adsense/300x250') ?>
                    <div class="kontextuaDisplayREGULARSS300x250"></div>
        <div style="margin-left: 10px; margin-right: 10px">

                    <div class="row-fluid">                    
<div class="span6"><?php echo html::link('random', '<i class="icon-random"></i> random','') ?></div>
<div class="span6"><?php echo html::link('topvisitas', '<i class="icon-thumbs-up"></i> Top Visitas','') ?></div>
</div>
                    
                    <hr><h4><i class="icon-th-list"></i> Categorias</h4><hr>
             <div style="width:100%; float:left; margin: 10px;">
                        <?php $categorias = Load::model('categorias')->find("order: rand()"); foreach ($categorias as $item) : ?>

                     <div class='caja_categoria'> <?php echo Html::link("categoria/$item->nombre/",$item->nombre) ?></div>
                     <?php endforeach; ?>

             </div> 
                           <div style="width:100%; float:left; margin-bottom: 15px;">
      
                    <hr><h4><i class="icon-building"></i> Ciudades</h4><hr>
             <ul>
                  <?php $ciudades = Load::model('ciudades')->find("order: rand()");
                        foreach ($ciudades as $itemc) : ?>
                 
                        <div class='caja_categoria'> <?php echo Html::link("clasificados/$itemc->nombre/",$itemc->nombre)?></div>
                       <?php  endforeach; ?><hr>
                           </div>
                    
                    <div class="row-fluid"><hr><h4><i class="icon-spinner icon-spin"></i> Permanece conectado:</h4><hr>
                    <a href="https://twitter.com/avisoya" class="twitter-follow-button" data-show-count="false" data-lang="es" data-size="large">Seguir a @avisoya</a>
                    <a href="https://twitter.com/share" class="twitter-share-button" data-via="avisoya" data-lang="es" data-size="large">Twittear</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </div>
                    
                    
                    <?php view::partial('portal/sponsor') ?>
                    

        </div>

