                <div class="page-header">
                    <span class="lead">Gratis Faciles y Rapidos</span>
                </div>

<div class="btn-group btn-group-justified">
    <?php echo html::link('random', '<i class="icon-random"></i> random','class="btn btn-danger"') ?>
    <?php echo html::link('topvisitas', '<i class="icon-thumbs-up"></i> Top Visitas','class="btn btn-danger"') ?>

      </div>
                    <?php // View::partial('adsense/300x250') ?>
                    <div class="kontextuaDisplayREGULARSS300x250"></div>
        <div style="margin-left: 10px; margin-right: 10px">

            <br>                    
             <div class="list-group">
                   <a href="#" class="list-group-item active"><i class="icon-th-list"></i> Categorias</a>

                 <?php $categorias = Load::model('categorias')->find("order: rand()"); foreach ($categorias as $item) : ?>
                 
                 <?php echo Html::link("categoria/$item->nombre/",$item->nombre,'class="list-group-item"') ?>
                     <?php endforeach; ?>

             </div> 
                    <div class="list-group">
      
                   <a href="#" class="list-group-item active"><i class="icon-building"></i> Ciudades</a>
             
                  <?php $ciudades = Load::model('ciudades')->find("order: rand()");
                        foreach ($ciudades as $itemc) : ?>
                 
                        <?php echo Html::link("clasificados/$itemc->nombre/",$itemc->nombre,'class="list-group-item"')?>
                       <?php  endforeach; ?>
                      </div>
                    
                    <div class="row"><hr><h4><i class="icon-spinner icon-spin"></i> Permanece conectado:</h4><hr>
                    <a href="https://twitter.com/avisoya" class="twitter-follow-button" data-show-count="false" data-lang="es" data-size="large">Seguir a @avisoya</a>
                    <a href="https://twitter.com/share" class="twitter-share-button" data-via="avisoya" data-lang="es" data-size="large">Twittear</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
                    </div>
                    
                    
                    <?php view::partial('portal/sponsor') ?>
                    
                    <center><?php echo html::img('portal/banner-avisoya.jpg','','class="img-responsive"') ?></center>
                    

        </div>

