<div class="row-fluid">
   
        <?php $i=0; $i2=0; foreach ($listClasificados->items as $item) : ?>
<div class="row-fluid">

        <div class="span12" style="padding-left:10px;padding-right:10px;">
            <strong><?php echo html::link("clasificado/$item->slug/", $item->titulo) ?></strong>
              <div class="" style="max-height:44px; overflow:hidden"><?php echo strip_tags($item->anuncio) ?> </div>
              <?php echo html::link("buscar/$item->categoria/",$item->categoria,'style="color:#e4004b;"') ?> - 
              <?php echo html::link("buscar/$item->ciudad/",$item->ciudad,'style="color:#e4004b;"') ?>
              <hr>
         </div><!--/span-->
</div><!--/row-fluid-->
    

     <?php   if ($i == 1) { ?>
            <div class="row-fluid"> 
                <div >
                    <center><?php View::partial('adsense/468x60')?></center>
                </div><hr>
            </div>
     
     <?php } $i += 1; ?>

            
            
     <?php   if ($i2 == 4) { ?>
            <div> 
                    <center><?php View::partial('adsense/468x60')?></center>
            </div><hr>
     
     <?php } $i2 += 1; ?>            
            
            
    <?php endforeach; ?>

    
    
    
    
</div>    

    <?php if(isset($url)) { ?>
    
      
      <?php View::partial('paginators/bootstrap', false, array('page' => $listClasificados, 'url'=>$url )); ?>
      <?php } else { ?>
        <?php View::partial('paginators/bootstrap', false, array('page' => $listClasificados )); ?>
      <?php } ?>


        <?php // View::partial('masonry') ?>
