   
        <?php $i=0; $i2=0; foreach ($listClasificados->items as $item) : ?>

        <div class="col-lg-12 info-ad" >
            <h3><?php echo html::link("clasificado/$item->slug/", $item->titulo) ?></h3>
              <div class="" style="max-height:44px; overflow:hidden"><p><?php echo strip_tags(mb_strtolower($item->anuncio ,'UTF-8')) ?> </p></div>
              <?php echo html::link("buscar/$item->categoria/",$item->categoria,'style="color:#e4004b;"') ?> - 
              <?php echo html::link("buscar/$item->ciudad/",$item->ciudad,'style="color:#e4004b;"') ?>
              <time class="timeago" datetime="<?php echo $item->registrado_at ; ?>"></time>

              <hr>
         </div><!--/span-->
    

     <?php   if ($i == 1) { ?>
                <div class="col-lg-12" >
                    <center><?php // View::partial('adsense/468x60')?><div class="kontextuaRT"></div></center>
                </div><hr>
     
     <?php } $i += 1; ?>

            
            
     <?php   if ($i2 == 4) { ?>
               <div class="col-lg-12" >
                   <center><?php // View::partial('adsense/468x60')?><div class="kontextuaRT"></div></center>
                   
               </div><hr>
     
     <?php } $i2 += 1; ?>            
            
            
    <?php endforeach; ?>

    
    
    
    

    <?php if(isset($url)) { ?>
    
      
      <?php View::partial('paginators/bootstrap', false, array('page' => $listClasificados, 'url'=>$url )); ?>
      <?php } else { ?>
        <?php View::partial('paginators/bootstrap', false, array('page' => $listClasificados )); ?>
      <?php } ?>


        <?php // View::partial('masonry') ?>
