<!--  javascript nicedit  -->
  <?php echo Tag::js('nicedit/nicEdit'); ?>

<!--  Fin javascript nicedit  -->

<script type="text/javascript">
bkLib.onDomLoaded(function(){
	nicEditors.allTextAreas(
		{buttonList : ['image','upload','left','center','right','bold','italic','underline','ol','ul',
'strikethrough','hr' ],
		iconsPath : 'http://avisoya.com/javascript/nicedit/nicEditorIcons.gif'})
	});
</script>