<hr><h4><i class="icon-group"></i> Patrocinadores</h4><hr>
<div class="row">
    <div class="col-md-6"><a href="http://servidigital.co" target="_blank"><img src="http://servidigital.co/wp-content/themes/bootstrapwp-Twitter-Bootstrap-for-WordPress/img/portal/servidigital.png" alt="Diseño web neiva" class="img-responsive"></a></div>
    <div class="col-md-6"><a href="http://autorallyneiva.com.co" target="_blank"><img src="http://autorallyneiva.com.co/wp-content/uploads/2013/01/escudo_autorally_neiva-300x284.png" alt="curso de manejo neiva" class="img-responsive"></a></div>
</div>


<div class="row">
    <div class="col-md-6"><a href="http://asconphu.com" target="_blank"><img src="http://www.asconphu.com/wp-content/uploads/2013/05/logo-asconphu.jpg" alt="Asociacion de contadores publicos" class="img-responsive"></a></div>
    <div class="col-md-6"><a href="http://saludocupacionaldelhuila.com.co" target="_blank"><img src="http://saludocupacionaldelhuila.com.co/wp-content/themes/soh/img/logo-soh-circle.png" alt="cursos de alturas neiva" class="img-responsive"></a></div>
</div>

<hr>

