<hr><h4><i class="icon-group"></i> Patrocinadores</h4><hr>
<div class="row-fluid">
    <div class="span6"><a href="http://servidigital.co" target="_blank"><img src="http://servidigital.co/wp-content/themes/bootstrapwp-Twitter-Bootstrap-for-WordPress/img/portal/servidigital.png" alt="Diseño web neiva"></a></div>
    <div class="span6"><a href="http://autorallyneiva.com.co" target="_blank"><img src="http://autorallyneiva.com.co/wp-content/uploads/2013/01/escudo_autorally_neiva-300x284.png" alt="curso de manejo neiva"></a></div>
</div>

<div class="row-fluid">
    <div class="span6"><a href="http://jlralturas.com" target="_blank"><img src="http://jlralturas.com/img/sitio2/logo.png" alt="cursos de alturas neiva"></a></div>
    <div class="span6"><a href="http://miscertificados.co" target="_blank"><img src="http://miscertificados.co/img/logo.png" alt="Plataforma de certificados Online"></a></div>
</div>

<div class="row-fluid">
    <div class="span6"><a href="http://asconphu.com" target="_blank"><img src="http://www.asconphu.com/wp-content/uploads/2013/05/logo-asconphu.jpg" alt="Asociacion de contadores publicos"></a></div>
    <div class="span6"><a href="http://saludocupacionaldelhuila.com.co" target="_blank"><img src="http://saludocupacionaldelhuila.com.co/wp-content/themes/soh/img/logo-soh-circle.png" alt="cursos de alturas neiva"></a></div>
</div>

<hr>
