<?php View::content() ?>
    
<!-- archivo /views/archivos/index.phtml -->
 
<?php View::content() ?>
<br/>
<h1>Subida de Imagen</h1>
<?php echo Form::openMultipart('archivos/index') ?>
    Ingrese una imagen .jpg , .gif ó .png :
    <?php echo Form::file('archivo') ?>
    <?php echo Form::hidden('oculto') //para saber si se envió el form ?>
    <?php echo Form::submit('subir') ?>
<?php echo Form::close() ?>