
<script type="text/javascript">
    var RecaptchaOptions = {
   lang: 'es',
   theme : 'clean'  // [ red, white, blackglass, clean, custom ]
  };
</script>




   <?php View::content(); ?>
<div class="caja">
<div class="page-header pd-l10"><h3>Clasificados Gratis Faciles y Rapidos</h3></div>

    <div class="row caja"> 

    <div class="col-md-8">    
        <center><h5><?php echo $msg; ?></h5></center>

        <div class="breadcrumb">
<br>
<div class="row">
    <div class="col-md-1"><img src='<?php echo $credentials->profile_image_url; ?>'/></div>
    <div class="col-md-3"><?php echo $credentials->screen_name ?></div>
    <div class="col-md-2"><a href='http://localhost/clasi-kumbia/oauth/_logout'>Logout</a></div>
</div>

   </div>
    
    
  
    <?php echo Form::openMultipart(NULL,"class='form-horizontal'") ; ?>
    <?php echo Form::hidden('clasificados.estatus',NULL, 1); ?>
    <?php // echo Form::hidden('clasificados.codigosecurity',NULL, 1); ?>
    <?php echo Form::hidden('clasificados.site',NULL, 'AV'); ?>
    <?php echo Form::hidden('clasificados.twitter_id',NULL, $credentials->id); ?>
    <?php echo Form::hidden('clasificados.id') ?>
    <?php echo Form::hidden('clasificados.codigosecurity');?>

  <div class="form-group">
    <label class="col-lg-2 control-label" for="selectCategoria">Categoria</label>
    <div class="col-lg-10">
          <?php echo Form::dbSelect('clasificados.categoria_id', 'nombre',array('categorias', 'find'), '-- seleccione categoria --','class="form-control" required') ?>
    </div>
  </div>        
    

  <div class="form-group">
    <label class="col-lg-2 control-label" for="SelectCiudad">Ciudad</label>
    <div class="col-lg-10">
    <?php echo Form::dbSelect('clasificados.ciudad_id', 'nombre',array('ciudades', 'find'), '-- seleccione Ciudad --','class="form-control"  required') ?>    </div>
  </div>        

  <div class="form-group">
    <label class="col-lg-2 control-label" for="inputTitulo">Titulo</label>
    <div class="col-lg-10">
        <?php  echo Form::text('clasificados.titulo','class="form-control"  maxlength="90" placeholder="Titulo del anuncio…" required'); ?>
    </div>
  </div> 

  <div class="form-group">
    <label class="col-lg-2 control-label" for="TextareaAnuncio">Anuncio</label>
    <div class="col-lg-10">
        <?php  echo Form::textarea('clasificados.anuncio','class="form-control"  rows="6" '); ?>
        <?php View::partial('portal/nicedit'); ?>
    </div>
  </div> 
        
           
        
        <div class="page-header pd-l10"><h3>Datos del Vendedor</h3></div>

  <div class="form-group">
    <label class="col-lg-2 control-label" for="inputEmail">Email</label>
    <div class="col-lg-10 ">
        <?php  echo Form::text('clasificados.email','class="form-control"  placeholder="Email Valido" required'); ?>
        
    </div>
  </div>
        

        


  <div class="form-group">
     <label class="col-lg-2 control-label"></label>
      <div class="col-lg-10 ">
          <label class="radio-inline">
              <?php echo Form::radio("clasificados.email_estado", '1', NULL, true);?> Mostrar Email  
          </label>
          
          <label class="radio-inline">
              <?php echo Form::radio("clasificados.email_estado", '0','class="radio"', false);?> No mostrar Email.
          </label>
      </div>
  </div>
        

        

  <div class="form-group">
    <label class="col-lg-2 control-label" for="inputTelefono">Telefono</label>
    <div class="col-lg-10">
        <?php  echo Form::text('clasificados.telefono','class="form-control"  placeholder="Telefono…" required'); ?>
    </div>
  </div>
        
        


        <br><center><button type="submit" class="btn btn-large btn-danger">Publicar Anuncio</button></center>

     <?php echo SecurityKey::generateKey(); ?>         
     <?php echo Form::close() ?>
        </div>
    <div class="col-md-4">
        <?php echo view::partial('adsense/300x600') ?>
    </div>
</div>
</div>