<div class="row caja" style="padding-top: 6px;padding-bottom: 0px;">
    <?php echo $clasificado->titulo ?>
    <div class="col-md-1"><img src='<?php echo $credentials->profile_image_url; ?>'/></div>
    <div class="col-md-3"><h3><?php echo $credentials->screen_name ?></h3></div>
    <div class="col-md-5"><center><h5><?php echo $msg; ?></h5></center> </div>
</div>
    <div class="row caja">
    <div class="col-md-12">

    <!--lista clasificados-->
 <?php View::partial('portal/lista-item-user', FALSE, array('listClasificados' => $listClasificados, 'url'=>"editar/pag")) ?>
<!--fin lista clasificados-->
    </div>
</div>