
<script type="text/javascript">
    var RecaptchaOptions = {
   lang: 'es',
   theme : 'clean'  // [ red, white, blackglass, clean, custom ]
  };
</script>

    <?php View::content(); ?>

<div class="row-fluid">
    <div class="span8 caja">
        <div class="well well-small"><span class="lead">Clasificados Gratis Faciles y Rapidos</span></div>

    <!--lista clasificados-->
 <?php View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados, 'url'=>"pag")) ?>
<!--fin lista clasificados-->
    </div>
    <!-- div class="span4 caja"  -->
    <?php view::partial('portal/lateral'); ?>
    <!-- fin div class="span4 caja"  -->


</div>

    
