 <script type="text/javascript">
function cambiar_opcion(combo){
    if(combo.value=='solo texto'){
     document.getElementById('imagen').style.display = 'none';
     document.getElementById('video').style.display = 'none';}

    else if(combo.value=='con imagen'){
     document.getElementById('imagen').style.display = 'block';
     document.getElementById('video').style.display = 'none';
    }
    if(combo.value=='con video'){
     document.getElementById('video').style.display = 'block';
     document.getElementById('imagen').style.display = 'none';

    }



    }
    </script>
 
<script type="text/javascript">
    var RecaptchaOptions = {
   lang: 'es',
   theme : 'clean'  // [ red, white, blackglass, clean, custom ]
  };
</script>

<script type="text/javascript">
 
$(document).ready(function(){
 
        $(".slidingDiv").hide();
        $(".show_hide").show();
 
    $('.show_hide').click(function(){
    $(".slidingDiv").slideToggle();
    });
 
});
 
</script>

<div class="container" style="margin-top: 8%">




   <?php View::content(); ?>


   
        
<!-- barra lateral izquierda nav   -->
        <?php // View::partial('portal/lateral') ?>
<!--fin barra lateral izquierda nav    -->

<div class="row">
<!--contenido-->
               <?php //View::partial('adsense/texto-imagen-728x90') ?>


<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="btn" data-toggle="modal">Launch demo modal</a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  </div>
  <div class="modal-body">
      
      <!-- formulario publicar aviso   -->
<?php View::partial('formulario', FALSE, array('previousError' => $previousError)) ?>
           
 
<!--  Fin formulario publicar aviso   -->

      
      
      
      
  </div>
  <div class="modal-footer">
    <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
    <button class="btn btn-primary">Save changes</button>
  </div>
</div>





    <Center><h3>Clasificados Gratis Faciles y Rapidos</h3></center><br><br>



<!--lista clasificados-->
 <?php View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados, 'url'=>"pag")) ?>


<!--fin lista clasificados-->
</div>
    
