
<script type="text/javascript">
    var RecaptchaOptions = {
   lang: 'es',
   theme : 'clean'  // [ red, white, blackglass, clean, custom ]
  };
</script>




   <?php View::content(); ?>
<div class="caja">
<div class="well well-small"><h3>Clasificados Gratis Faciles y Rapidos</h3></div>

    <div class="row-fluid"> 

    <div class="span8 caja">    
        <center><h5><?php echo $msg; ?></h5></center>

        <div class="breadcrumb">
<br>
<div class="row-fluid">
    <div class="span1"><img src='<?php echo $credentials->profile_image_url; ?>'/></div>
    <div class="span3"><?php echo $credentials->screen_name ?></div>
    <div class="span2"><a href='http://avisoya.com/oauth/_logout'>Logout</a></div>
</div>

   </div>
    
    
  
    <?php echo Form::openMultipart(NULL,"class='form-horizontal'") ; ?>
    <?php echo Form::hidden('clasificados.estatus',NULL, 1); ?>
    <?php echo Form::hidden('clasificados.vendido',NULL, 0); ?>
    <?php echo Form::hidden('clasificados.site',NULL, 'AV'); ?>
    <?php echo Form::hidden('clasificados.twitter_id',NULL, $credentials->id); ?>
    
  <div class="control-group">
    <label class="control-label st" for="selectCategoria">Categoria</label>
    <div class="controls">
          <?php echo Form::dbSelect('clasificados.categoria_id', 'nombre',array('categorias', 'find'), '-- seleccione categoria --','class="input-block-level" required') ?>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label st" for="SelectCiudad">Ciudad</label>
    <div class="controls">
    <?php echo Form::dbSelect('clasificados.ciudad_id', 'nombre',array('ciudades', 'find'), '-- seleccione Ciudad --','class="input-block-level" required') ?>    </div>
  </div>

  <div class="control-group">
    <label class="control-label st" for="inputTitulo">Titulo</label>
    <div class="controls">
        <?php  echo Form::text('clasificados.titulo','class="input-block-level" maxlength="90" placeholder="Titulo del anuncio…" required'); ?>
    </div>
  </div> 
        
        
  <div class="control-group">
    <label class="control-label st" for="TextareaAnuncio">Anuncio</label>
    <div class="controls">
        <?php  echo Form::textarea('clasificados.anuncio','class="input-block-level" rows="6" '); ?>
        <?php View::partial('portal/nicedit'); ?>
    </div>
  </div>        

        
        <div class="well well-small"><h3>Datos del Vendedor</h3></div>

  <div class="control-group">
    <label class="control-label st" for="inputEmail">Email</label>
    <div class="controls ">
        <?php  echo Form::text('clasificados.email','class="input-block-level" placeholder="Email Valido" required'); ?>
        
    </div>
  </div>
        


  <div class="control-group">
    <label class="control-label st" for="inputEmail"></label>
    <div class="controls ">
<?php echo Form::radio("clasificados.email_estado", '1', NULL, true);?> Mostrar Email  
<?php echo Form::radio("clasificados.email_estado", '0','class="radio" style="margin-left:10px;"', false);?> No mostrar Email.        
    </div>
  </div>        
        

        

  <div class="control-group">
    <label class="control-label st" for="inputTelefono">Telefono</label>
    <div class="controls">
        <?php  echo Form::text('clasificados.telefono','class="input-block-level" placeholder="Telefono…" required'); ?>
    </div>
  </div>


  <div class="control-group">
    <label class="control-label st" for="recaptcha">Antispam</label>
    <div class="controls">
               <?php echo reCaptcha::html($previousError); // Cargamos la librería y le pedimos un código html ?>

    </div>
  </div>

        <br><center><button type="submit" class="btn btn-large btn-danger">Publicar Anuncio</button></center>

     <?php echo SecurityKey::generateKey(); ?>         
     <?php echo Form::close() ?>
        </div>
    <div class="span4">
        <?php echo view::partial('adsense/300x600') ?>
    </div>
</div>
</div>