
<script type="text/javascript">
    var RecaptchaOptions = {
   lang: 'es',
   theme : 'clean'  // [ red, white, blackglass, clean, custom ]
  };
</script>



<!--para el textarea-->
<script type="text/javascript">
$(document).ready(function(){    
  $('#clasificados_nombre').maxlength({   
    events: [], // Array of events to be triggerd    
    maxCharacters: 360, // Characters limit   
    status: true, // True to show status indicator bewlow the element    
    statusClass: "status", // The class on the status div  
    statusText: "Caracteres", // The status text  
    notificationClass: "notification",	// Will be added when maxlength is reached  
    showAlert: true, // True to show a regular alert message    
    alertText: "Excedio la Cantidad de Caracteres Permitidos", // Text in alert message   
    slider: false // True Use counter slider    
  }); 
});
</script> 


<div class="barra"><a data-dismiss="modal" aria-hidden="true" class="ico"><i class="icon-reply icon-2x" style="margin-top: 60px;"></i></a></div>
<hr>
<div class="container">
   <?php View::content(); ?>


  
    <?php echo Form::openMultipart(NULL,"class='general'") ; ?>
    <?php echo Form::hidden('clasificados.estatus',NULL, 1); ?>
    <?php echo Form::hidden('clasificados.codigosecurity',NULL, 1); ?>
    <?php echo Form::hidden('clasificados.site',NULL, 'AV'); ?>
    
    <?php echo Form::dbSelect('clasificados.idcategoria_FK', 'nombre',array('categorias', 'find'), '-- seleccione categoria --','class="input-block-level" required') ?>
    <?php echo Form::dbSelect('clasificados.idciudad_FK', 'nombre',array('ciudades', 'find'), '-- seleccione Ciudad --','class="input-block-level" required') ?>
    <?php  echo Form::textarea('clasificados.nombre','class="input-block-level"  placeholder="Descripcion del anuncio…"rows="6" required'); ?>
    <?php echo Form::text('clasificados.email','class="input-block-level" placeholder="Email..."  required','') ?>
    
   <center> 
       <?php Load::Lib("recaptcha"); // Cargamos la librería y le pedimos un código html
	echo reCaptcha::html($previousError);?>
   </center>    

<div class="form-actions">
  <button type="submit" class="btn btn-primary">Publicar Anuncio</button>
</div>

        <?php echo SecurityKey::generateKey(); ?>              
     <?php echo Form::close() ?>
</div>