<?php View::content(); ?>
<?php // View::partial('adsense/970x90h') ?>
<!-- <div class="kontextuaDisplayELEVATOR"></div> -->

<div class="row caja">

    
    <div class="col-md-8">   
<?php if($mostrar):?>    

    
<!--lista clasificados-->
<?php if ($clasificado->vendido == 1){ flash::error('Esta Publicacion se encuentra vendida');}?>

<div class=""> 
    <h3 style="color:#000; padding: 0px 10px 0px 10px;"><?php echo strip_tags($clasificado->titulo) ?> </h3><hr>
    <div style="padding: 0px 10px 0px 10px;"><?php echo $clasificado->anuncio ?> </div>
                        

    
    
</div>
<div class="breadcrumb">

<span style="color:#e4004b; font-weight: bold">Visitas </span><?php echo $clasificado->visitas ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span style="color:#e4004b; font-weight: bold">Categoria </span><?php echo $obtcate ?>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<span style="color:#e4004b; font-weight: bold">Ubicacion </span><?php echo $ciudad ?>


    <div class="pull-right">
        
        
        
        <!-- Lockerz Share BEGIN -->
<div class="a2a_kit a2a_default_style">

<a class="a2a_button_facebook"></a>
<a class="a2a_button_twitter"></a>
<a class="a2a_button_google_plus"></a>
<a class="a2a_button_email"></a>
<a class="a2a_dd" href="http://www.addtoany.com/share_save"></a>

</div>
<script type="text/javascript">
var a2a_config = a2a_config || {};
a2a_config.onclick = 1;
a2a_config.locale = "es";
</script>
<script type="text/javascript" src="http://static.addtoany.com/menu/page.js"></script>
<!-- Lockerz Share END -->
     
    </div>

</div>


<!-- cuadro imagen se muestra si hay imagen en el clasificado-->
<?php  if (!empty($clasificado->img)){ 

 echo "<div Class='barra-imagenes'>";
 echo Html::link("img/upload/$clasificado->img",Html::img("upload/$clasificado->img",'',''),'target="_blank"');
  echo Html::link("img/upload/$clasificado->img2",Html::img("upload/$clasificado->img2",'',''),'target="_blank"');
   echo Html::link("img/upload/$clasificado->img3",Html::img("upload/$clasificado->img3",'',''),'target="_blank"'); 
 
 
 echo "</div>";

} 
   ?>
<!-- fin cuadro-->




<br>
<div id="disqus_thread">
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'avisoya'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>
Por favor Habilite el  JavaScript 
</noscript>
  </div>
    </div>

<!--fin lista clasificados-->
<?php endif;?>


<div class="col-md-4">   
<!-- barra lateral izquierda nav   -->
        <?php //View::partial('portal/lateral') ?>
        <?php //View::partial('adsense/160x600') ?>
        <?php // view::partial('adsense/300x250') ?>

<div class="">
                  <div class="page-header">
                    <span class="lead">Contacta al vendedor</span>
                </div>
    <div style="padding: 10px">
    <script type="text/javascript">
    $(function(){
    init();
});
    // Guardar el número y una copia con las XXXX
    var numero = "<?php echo $clasificado->telefono; ?>";
    var numeroParcial = numero.substring(0, 3) + "XXXX";
    
    // se ejcuta al cargar
   function init(){
         // poner el numero parcial de entrada
        document.getElementById("numero").innerHTML = numeroParcial;
    }
    
    // funcion que muestra el numero completo al dar click
    function mostrarNumero(){
        document.getElementById("numero").innerHTML = numero;
    }
    </script>
    <div>

        
        
        <h3 style="color:#e4004b;"><i class="icon-phone"></i> <span id="numero"><?php echo $clasificado->telefono; ?></span></span>
        <a href="#" onclick="mostrarNumero() "style="font-size:0.7em;">Ver Telefono</a></h3>
        <div class="mentel">Cuando llame diga que vio el numero en avisoya </div>
    </div>    
    
    
    <?php if ($clasificado->email_estado == 1){ ?> <h5> <i class="icon-envelope"></i> <?php echo $clasificado->email ?></h5><?php }?>
    <h5><i class="icon-map-marker"></i> <?php echo $ciudad.', Colombia'  ?></h5>
    <h5><i class="icon-time"></i> <?php echo $clasificado->registrado_at  ?></h5>
    </div>
</div>


<div><?php echo html::link('random', '<i class="icon-random"></i> random','class="btn btn-primary btn-lg" style="width:100%;"') ?></div>
    
    </div>


    </div>


