<!--Categorias-->
    <div class="row-fluid caja">

        <div class="page-header"><h3 class="lead">Categoria <?php echo $barrainfocate ?></h3></div>

<!--lista clasificados-->

 <?php // View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados)) ?>

<?php View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados, 'url'=>"categoria/$categoria")) ?>
<!--fin lista clasificados-->

    </div>
