<!--Categorias-->

<table width="100%" border="0" align="center">
<tr>
   
<!--tabla-->
    <td width="18%" valign="top">   
<!-- barra lateral izquierda nav   -->
        <?php View::partial('portal/lateral') ?>
    </td>  
<!--fin barra lateral izquierda nav    -->

    <td width="82%" valign="top">
   <div id="br-info">Categoria <?php echo $barrainfocate ?></div>

<!--adsense-->
 <?php View::partial('adsense/doble336x280') ?>
<!--fin adsense-->


<!--lista clasificados-->

 <?php // View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados)) ?>

<?php View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados, 'url'=>"categoria/$categoria")) ?>
<!--fin lista clasificados-->
    </td>
    </tr>
</table>

