<!--Categorias-->
    <div class="row-fluid caja">

        <h3>Categoria <?php echo $barrainfocate ?></h3><hr>

<!--lista clasificados-->

 <?php // View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados)) ?>

<?php View::partial('portal/lista-item', FALSE, array('listClasificados' => $listClasificados, 'url'=>"categoria/$categoria")) ?>
<!--fin lista clasificados-->

    </div>
