<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta name="Description" content="<?php echo $pageDescription ?>"/> 

  <title><?php echo $pageTitle ?></title>
     <?php Tag::css('b231/bootstrap') ?>
     <?php Tag::css('b231/bootstrap-responsive') ?>
     <?php Tag::css('font-awesome.min')?>
     <?php Tag::css('b231/style')?>  
     <?php Tag::css('icon-social/zocial')?>  
     <?php //Tag::css('base')?>  
         
         
  <?php // Tag::css('bienvenida') ?>
  <?php Tag::css('style') ?>
  <?php // Tag::css('scaffold') ?>
  <?php // Tag::css('estilo') ?>
  
  <?php echo Html::includeCss() ?>
  
  <?php // echo Tag::js('jquery/jquery.maxlength-min');?>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="js/jquery-1.8.3.min.js"%3E%3C/script%3E'))</script>

 
 </head>
 <body><div class="container-980">
        <?php View::partial('portal/header') ?>

        <?php View::content(); ?>

        <?php View::partial('portal/footer') ?>
     </div>
    
     
    
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-11364905-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>     
     

</body>
    <?php echo  Tag::js('bootstrap')?>


</html>
