<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <meta name="Description" content="<?php echo $pageDescription ?>"/> 
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
    <link rel="shortcut icon" href="<?php echo PUBLIC_PATH ?>public/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="<?php echo PUBLIC_PATH ?>public/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="<?php echo PUBLIC_PATH ?>public/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="<?php echo PUBLIC_PATH ?>public/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed"
          href="<?php echo PUBLIC_PATH ?>public/ico/apple-touch-icon-57-precomposed.png">


  <title><?php echo $pageTitle ?></title>
     <?php Tag::css('b3/bootstrap') ?>
     <?php Tag::css('font-awesome.min')?>
     <?php Tag::css('b231/style')?>  
     <?php Tag::css('icon-social/zocial')?>  
     <?php Tag::css('animate/animate')?>  
     <?php //Tag::css('base')?>  
     <?php Tag::css('style') ?>
  
  <?php echo Html::includeCss() ?>
  
  <?php // echo Tag::js('jquery/jquery.maxlength-min');?>
  
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  <script>!window.jQuery && document.write(unescape('%3Cscript src="js/jquery-1.8.3.min.js"%3E%3C/script%3E'))</script>

 
 </head>
 <body><div class="container">
        <?php View::partial('portal/header') ?>
         


<?php echo Form::open('buscar/','GET'); // por defecto llama a la misma url ?>
      <div class="col-lg-12 animated bounceInDown" style="margin:10px;">
          <div class="input-group">
              <?php echo Form::text('b','class="form-control input-lg" placeholder="Buscar Clasificados"'); ?>
              <span class="input-group-btn">
                <button type="button" class="btn btn-default"><i class="icon-search icon-2x"></i></button>                  
              </span>

          </div>
          
      </div>
<?php echo Form::close() ?>

         
        <?php View::content(); ?>

        <?php View::partial('portal/footer') ?>
     </div>
    
     
    
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-11364905-9']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>     
     

</body>
    <?php echo  Tag::js('b3/bootstrap')?>
    <?php echo  Tag::js('jquery.timeago')?>
<script>
    jQuery(document).ready(function() {
        jQuery("time.timeago").timeago();
    });
</script>
 <!--   <script src="http://cf.ads.kontextua.com/container/tags/37275.js"></script>  -->


</html>
