<?php $apiKey = "";?>

<style type="text/css">
.mimapa{width:500px;height:500px;}
</style>

<? echo '<div id="mimapa" class="mimapa"></div>'; ?>
<script type="text/javascript">
	var mimapa;
	var gmarkers = new Array();

        function initialize(){
		if(GBrowserIsCompatible()){
                        //creamos un nuevo mapa
			mimapa = new GMap2(document.getElementById("mimapa"));
                        //establecemos cual es el centro del mapa
                        center = new GLatLng(<?php echo $centro['lat'];?>, <?php echo $centro['lng'];?>);
			mimapa.setCenter(center, <?php echo $centro['zoom'];?>);
                        //seleccionamos la interzaz del mapa
                        mimapa.setUIToDefault();

                        //por cada coordenada que se envie se crea un punto
                       <?php foreach ($puntos as $punto){?>
                           var point = new GLatLng(<?= $punto['lat']?>,<?= $punto['lng']?>);
                          mimapa.addOverlay(new GMarker(point));
                        <?php }?>
                 }
         }
</script>

<?php echo "<script type='text/javascript' src='http://maps.google.com/maps?file=api&;v=2&key=".$apiKey."&async=2&callback=initialize'></script>"; ?>