<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Error 404 archivo no disponible</title>
    <link rel="stylesheet" href="<?php echo PUBLIC_PATH ?>css/style.css" />
</head>
<body style="background-color: #fdfdfd;">

    <div style="text-align: center; margin: 50px; font-size: 12pt; background-color: transparent; font-family: Lucida Grande, Verdana, Sans-serif;">
        <table align="center" id="content" style="background-color: #fff; border: #999 1px solid; padding: 10px 10px 6px 10px; width: 50%;">
            <tbody>
                <tr>
                    <td style="width: 5%">
                        <a href="http://avisoya.com"><img src="<?php echo PUBLIC_PATH ?>img/logo-avisoya.png" alt="clasificados Avisoya"/></a>
                        <a>Clasificados Avisoya la facilidad y sencillez que todos necesitan :)</a>
                    </td>
                    <td>
                        <h1 style="font-size: 18pt; color: #990000; margin: 0 0 4px 0;">ERROR 404</h1>
                    </td>
                </tr>
                <tr>
                    <td><h2>Solicitud no disponible</h2></td>

                    <td><h2><?php echo Html::link('','Ir a Inicio'); ?></h2></td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>
