<?php View::content(); ?>
<br><div  id="scaffold"> 
<?php echo Form::open(); // por defecto llama a la misma url ?>
 
        <label>Nombre
        <?php echo Form::text('clasificados.titulo') ?></label>
 
        <label>Anuncio
        <?php echo Form::textarea('clasificados.anuncio') ?></label>

        <label>Visitas
        <?php echo Form::text('clasificados.visitas') ?></label>
 
        <label>email
        <?php echo Form::text('clasificados.email') ?></label>
    
        <label>ciudad_id
        <?php echo Form::text('clasificados.ciudad_id') ?></label>
    
        <label>twitter_id
        <?php echo Form::text('clasificados.twitter_id') ?></label>
        
        <label>code codigosecurity
        <?php echo Form::text('clasificados.codigosecurity') ?></label>
 
        <label>site
        <?php echo Form::text('clasificados.site') ?></label>
        
        <label>fecha_baja
        <?php echo Form::text('clasificados.registrado_at') ?></label>
        <label>Categoria
        <?php echo Form::dbSelect('clasificados.categoria_id', 'nombre',array('categorias', 'find'), '-- seleccione categoria --') ?></label>

        <label>Vendido
        <?php echo Form::text('clasificados.vendido') ?></label>
    
        <label>Estatus
    
        <?php echo estatus::select('clasificados') ?></label>
        
        
        <?php echo Form::hidden('clasificados.id') ?>
        <?php echo Form::submit('Actualizar') ?>
 
<?php echo Form::close() ?>
    <div class="actions">
        <?php echo Html::linkAction('', 'Listar') ?>
    </div>
</div>
        
        
        
     